name: Test Nuxt Build
on:
  push:
    branches-ignore:
      - staging
      - production
    # paths:
    #   - '**.vue'
    #   - '**.js'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm cache dir)"

      - uses: actions/cache@v1
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      -
        name: ğŸ”¨ Install our dependencies
        run: pnpm install
      -
        name: ğŸ‘¨â€ğŸ’»ï¸ Run a build
        run: pnpm build
